version '3'

services:
  proxy:
    image: chkeller/gradle-sandbox-proxy:${TAG}
    ports:
      - "80:80"
    networks:
      - test

  frontend:
    image: chkeller/gradle-sandbox-frontend:${TAG}
    networks:
      - test

  backend:
    image: chkeller/gradle-sandbox-backend:${TAG}
    networks:
      - test

networks:
  test:
    driver: bridge
